import { chromium } from "playwright";
const NEN = "https://ifan-web.vercel.app";
const CENT = "C:/Users/Admin/AppData/Local/CentBrowser/Application/chrome.exe";
const b = await chromium.launch({ executablePath: CENT, headless: true });
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, locale: "vi-VN" });
const page = await ctx.newPage();
const loi = [];
page.on("console", (m) => { if (m.type() === "error") loi.push(m.text().slice(0, 140)); });
await page.goto(`${NEN}/login`, { waitUntil: "domcontentloaded" });
await page.fill("#identifier", "demo.ifan.2026@gmail.com");
await page.fill("#password", "DemoIfan#2026");
await page.click('button[type="submit"]');
await page.waitForURL(/\/app/, { timeout: 45000 });
await page.goto(`${NEN}/app/chat`, { waitUntil: "networkidle" });
await page.waitForTimeout(2200);
await page.screenshot({ path: "scratchpad-chat.png" });
console.log("loi do:", loi.length, loi[0] ?? "");
await b.close();
